// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estudos_crud.Data;

#nullable disable

namespace estudoscrud.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230208011008_UpdateTableUsersCars")]
    partial class UpdateTableUsersCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("estudos_crud.Models.UserCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("palte");

                    b.Property<DateTime>("RegisterCar")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("registerCar");

                    b.HasKey("Id");

                    b.ToTable("tb_usersCars", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
